version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:sha256-ff15e3911c1420a4820abd86523d39f7f210bb50178c1edebf0beda9e8016a8f
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"   # Expose the Elasticsearch port
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
