version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"   # Expose the Elasticsearch port
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/"]
      interval: 30s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    ports:
      - "5601:5601"   # Expose the Kibana port
    networks:
      - elastic
  Weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:latest
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      PLAYGROUND_ENABLED: "true"
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
  playground:
    image: semitechnologies/weaviate-playground:latest
    ports:
      - "3000:80"
    environment:
      - WEAVIATE_HOST=http://weaviate:8080
    depends_on:
      - Weaviate

networks:
  elastic:
    driver: bridge
volumes:
  weaviate_data: